package sjtu.opennet.multiproto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: multicast.proto

public final class Multicast {
  private Multicast() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface packetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 index = 1;</code>
     */
    int getIndex();

    /**
     * <pre>
     *meta为空，其他为文件数据
     * </pre>
     *
     * <code>bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>string threadId = 3;</code>
     */
    java.lang.String getThreadId();
    /**
     * <code>string threadId = 3;</code>
     */
    com.google.protobuf.ByteString
        getThreadIdBytes();

    /**
     * <code>string fileName = 4;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>string fileName = 4;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <pre>
     *文件id
     * </pre>
     *
     * <code>string fileId = 5;</code>
     */
    java.lang.String getFileId();
    /**
     * <pre>
     *文件id
     * </pre>
     *
     * <code>string fileId = 5;</code>
     */
    com.google.protobuf.ByteString
        getFileIdBytes();

    /**
     * <code>.google.protobuf.Timestamp sendTime = 6;</code>
     */
    boolean hasSendTime();
    /**
     * <code>.google.protobuf.Timestamp sendTime = 6;</code>
     */
    com.google.protobuf.Timestamp getSendTime();
    /**
     * <code>.google.protobuf.Timestamp sendTime = 6;</code>
     */
    com.google.protobuf.TimestampOrBuilder getSendTimeOrBuilder();

    /**
     * <code>int32 packetType = 7;</code>
     */
    int getPacketType();

    /**
     * <code>string sender = 8;</code>
     */
    java.lang.String getSender();
    /**
     * <code>string sender = 8;</code>
     */
    com.google.protobuf.ByteString
        getSenderBytes();
  }
  /**
   * Protobuf type {@code packet}
   */
  public  static final class packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:packet)
      packetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use packet.newBuilder() to construct.
    private packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private packet() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      threadId_ = "";
      fileName_ = "";
      fileId_ = "";
      sender_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new packet();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              index_ = input.readInt32();
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              threadId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              fileId_ = s;
              break;
            }
            case 50: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (sendTime_ != null) {
                subBuilder = sendTime_.toBuilder();
              }
              sendTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sendTime_);
                sendTime_ = subBuilder.buildPartial();
              }

              break;
            }
            case 56: {

              packetType_ = input.readInt32();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              sender_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Multicast.internal_static_packet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Multicast.internal_static_packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Multicast.packet.class, Multicast.packet.Builder.class);
    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_;
    /**
     * <code>int32 index = 1;</code>
     */
    public int getIndex() {
      return index_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     *meta为空，其他为文件数据
     * </pre>
     *
     * <code>bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int THREADID_FIELD_NUMBER = 3;
    private volatile java.lang.Object threadId_;
    /**
     * <code>string threadId = 3;</code>
     */
    public java.lang.String getThreadId() {
      java.lang.Object ref = threadId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        threadId_ = s;
        return s;
      }
    }
    /**
     * <code>string threadId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getThreadIdBytes() {
      java.lang.Object ref = threadId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        threadId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILENAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object fileName_;
    /**
     * <code>string fileName = 4;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string fileName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILEID_FIELD_NUMBER = 5;
    private volatile java.lang.Object fileId_;
    /**
     * <pre>
     *文件id
     * </pre>
     *
     * <code>string fileId = 5;</code>
     */
    public java.lang.String getFileId() {
      java.lang.Object ref = fileId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *文件id
     * </pre>
     *
     * <code>string fileId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFileIdBytes() {
      java.lang.Object ref = fileId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDTIME_FIELD_NUMBER = 6;
    private com.google.protobuf.Timestamp sendTime_;
    /**
     * <code>.google.protobuf.Timestamp sendTime = 6;</code>
     */
    public boolean hasSendTime() {
      return sendTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp sendTime = 6;</code>
     */
    public com.google.protobuf.Timestamp getSendTime() {
      return sendTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp sendTime = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getSendTimeOrBuilder() {
      return getSendTime();
    }

    public static final int PACKETTYPE_FIELD_NUMBER = 7;
    private int packetType_;
    /**
     * <code>int32 packetType = 7;</code>
     */
    public int getPacketType() {
      return packetType_;
    }

    public static final int SENDER_FIELD_NUMBER = 8;
    private volatile java.lang.Object sender_;
    /**
     * <code>string sender = 8;</code>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      }
    }
    /**
     * <code>string sender = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (index_ != 0) {
        output.writeInt32(1, index_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      if (!getThreadIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, threadId_);
      }
      if (!getFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fileName_);
      }
      if (!getFileIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, fileId_);
      }
      if (sendTime_ != null) {
        output.writeMessage(6, getSendTime());
      }
      if (packetType_ != 0) {
        output.writeInt32(7, packetType_);
      }
      if (!getSenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, sender_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, index_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (!getThreadIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, threadId_);
      }
      if (!getFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fileName_);
      }
      if (!getFileIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, fileId_);
      }
      if (sendTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getSendTime());
      }
      if (packetType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, packetType_);
      }
      if (!getSenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, sender_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Multicast.packet)) {
        return super.equals(obj);
      }
      Multicast.packet other = (Multicast.packet) obj;

      if (getIndex()
          != other.getIndex()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getThreadId()
          .equals(other.getThreadId())) return false;
      if (!getFileName()
          .equals(other.getFileName())) return false;
      if (!getFileId()
          .equals(other.getFileId())) return false;
      if (hasSendTime() != other.hasSendTime()) return false;
      if (hasSendTime()) {
        if (!getSendTime()
            .equals(other.getSendTime())) return false;
      }
      if (getPacketType()
          != other.getPacketType()) return false;
      if (!getSender()
          .equals(other.getSender())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + THREADID_FIELD_NUMBER;
      hash = (53 * hash) + getThreadId().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + FILEID_FIELD_NUMBER;
      hash = (53 * hash) + getFileId().hashCode();
      if (hasSendTime()) {
        hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + getSendTime().hashCode();
      }
      hash = (37 * hash) + PACKETTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getPacketType();
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Multicast.packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Multicast.packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Multicast.packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Multicast.packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Multicast.packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Multicast.packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Multicast.packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Multicast.packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Multicast.packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Multicast.packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Multicast.packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Multicast.packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Multicast.packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:packet)
        Multicast.packetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Multicast.internal_static_packet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Multicast.internal_static_packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Multicast.packet.class, Multicast.packet.Builder.class);
      }

      // Construct using Multicast.packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        index_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        threadId_ = "";

        fileName_ = "";

        fileId_ = "";

        if (sendTimeBuilder_ == null) {
          sendTime_ = null;
        } else {
          sendTime_ = null;
          sendTimeBuilder_ = null;
        }
        packetType_ = 0;

        sender_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Multicast.internal_static_packet_descriptor;
      }

      @java.lang.Override
      public Multicast.packet getDefaultInstanceForType() {
        return Multicast.packet.getDefaultInstance();
      }

      @java.lang.Override
      public Multicast.packet build() {
        Multicast.packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Multicast.packet buildPartial() {
        Multicast.packet result = new Multicast.packet(this);
        result.index_ = index_;
        result.data_ = data_;
        result.threadId_ = threadId_;
        result.fileName_ = fileName_;
        result.fileId_ = fileId_;
        if (sendTimeBuilder_ == null) {
          result.sendTime_ = sendTime_;
        } else {
          result.sendTime_ = sendTimeBuilder_.build();
        }
        result.packetType_ = packetType_;
        result.sender_ = sender_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Multicast.packet) {
          return mergeFrom((Multicast.packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Multicast.packet other) {
        if (other == Multicast.packet.getDefaultInstance()) return this;
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (!other.getThreadId().isEmpty()) {
          threadId_ = other.threadId_;
          onChanged();
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (!other.getFileId().isEmpty()) {
          fileId_ = other.fileId_;
          onChanged();
        }
        if (other.hasSendTime()) {
          mergeSendTime(other.getSendTime());
        }
        if (other.getPacketType() != 0) {
          setPacketType(other.getPacketType());
        }
        if (!other.getSender().isEmpty()) {
          sender_ = other.sender_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Multicast.packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Multicast.packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int index_ ;
      /**
       * <code>int32 index = 1;</code>
       */
      public int getIndex() {
        return index_;
      }
      /**
       * <code>int32 index = 1;</code>
       */
      public Builder setIndex(int value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 index = 1;</code>
       */
      public Builder clearIndex() {
        
        index_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *meta为空，其他为文件数据
       * </pre>
       *
       * <code>bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       *meta为空，其他为文件数据
       * </pre>
       *
       * <code>bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *meta为空，其他为文件数据
       * </pre>
       *
       * <code>bytes data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private java.lang.Object threadId_ = "";
      /**
       * <code>string threadId = 3;</code>
       */
      public java.lang.String getThreadId() {
        java.lang.Object ref = threadId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          threadId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string threadId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getThreadIdBytes() {
        java.lang.Object ref = threadId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          threadId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string threadId = 3;</code>
       */
      public Builder setThreadId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        threadId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string threadId = 3;</code>
       */
      public Builder clearThreadId() {
        
        threadId_ = getDefaultInstance().getThreadId();
        onChanged();
        return this;
      }
      /**
       * <code>string threadId = 3;</code>
       */
      public Builder setThreadIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        threadId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>string fileName = 4;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileName = 4;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 4;</code>
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 4;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fileId_ = "";
      /**
       * <pre>
       *文件id
       * </pre>
       *
       * <code>string fileId = 5;</code>
       */
      public java.lang.String getFileId() {
        java.lang.Object ref = fileId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *文件id
       * </pre>
       *
       * <code>string fileId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFileIdBytes() {
        java.lang.Object ref = fileId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *文件id
       * </pre>
       *
       * <code>string fileId = 5;</code>
       */
      public Builder setFileId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *文件id
       * </pre>
       *
       * <code>string fileId = 5;</code>
       */
      public Builder clearFileId() {
        
        fileId_ = getDefaultInstance().getFileId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *文件id
       * </pre>
       *
       * <code>string fileId = 5;</code>
       */
      public Builder setFileIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp sendTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> sendTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp sendTime = 6;</code>
       */
      public boolean hasSendTime() {
        return sendTimeBuilder_ != null || sendTime_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 6;</code>
       */
      public com.google.protobuf.Timestamp getSendTime() {
        if (sendTimeBuilder_ == null) {
          return sendTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
        } else {
          return sendTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 6;</code>
       */
      public Builder setSendTime(com.google.protobuf.Timestamp value) {
        if (sendTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sendTime_ = value;
          onChanged();
        } else {
          sendTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 6;</code>
       */
      public Builder setSendTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (sendTimeBuilder_ == null) {
          sendTime_ = builderForValue.build();
          onChanged();
        } else {
          sendTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 6;</code>
       */
      public Builder mergeSendTime(com.google.protobuf.Timestamp value) {
        if (sendTimeBuilder_ == null) {
          if (sendTime_ != null) {
            sendTime_ =
              com.google.protobuf.Timestamp.newBuilder(sendTime_).mergeFrom(value).buildPartial();
          } else {
            sendTime_ = value;
          }
          onChanged();
        } else {
          sendTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 6;</code>
       */
      public Builder clearSendTime() {
        if (sendTimeBuilder_ == null) {
          sendTime_ = null;
          onChanged();
        } else {
          sendTime_ = null;
          sendTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 6;</code>
       */
      public com.google.protobuf.Timestamp.Builder getSendTimeBuilder() {
        
        onChanged();
        return getSendTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 6;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getSendTimeOrBuilder() {
        if (sendTimeBuilder_ != null) {
          return sendTimeBuilder_.getMessageOrBuilder();
        } else {
          return sendTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp sendTime = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getSendTimeFieldBuilder() {
        if (sendTimeBuilder_ == null) {
          sendTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getSendTime(),
                  getParentForChildren(),
                  isClean());
          sendTime_ = null;
        }
        return sendTimeBuilder_;
      }

      private int packetType_ ;
      /**
       * <code>int32 packetType = 7;</code>
       */
      public int getPacketType() {
        return packetType_;
      }
      /**
       * <code>int32 packetType = 7;</code>
       */
      public Builder setPacketType(int value) {
        
        packetType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 packetType = 7;</code>
       */
      public Builder clearPacketType() {
        
        packetType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sender_ = "";
      /**
       * <code>string sender = 8;</code>
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sender = 8;</code>
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sender = 8;</code>
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sender = 8;</code>
       */
      public Builder clearSender() {
        
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <code>string sender = 8;</code>
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sender_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:packet)
    }

    // @@protoc_insertion_point(class_scope:packet)
    private static final Multicast.packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Multicast.packet();
    }

    public static Multicast.packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<packet>
        PARSER = new com.google.protobuf.AbstractParser<packet>() {
      @java.lang.Override
      public packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<packet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Multicast.packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017multicast.proto\032\037google/protobuf/times" +
      "tamp.proto\"\253\001\n\006packet\022\r\n\005index\030\001 \001(\005\022\014\n\004" +
      "data\030\002 \001(\014\022\020\n\010threadId\030\003 \001(\t\022\020\n\010fileName" +
      "\030\004 \001(\t\022\016\n\006fileId\030\005 \001(\t\022,\n\010sendTime\030\006 \001(\013" +
      "2\032.google.protobuf.Timestamp\022\022\n\npacketTy" +
      "pe\030\007 \001(\005\022\016\n\006sender\030\010 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_packet_descriptor,
        new java.lang.String[] { "Index", "Data", "ThreadId", "FileName", "FileId", "SendTime", "PacketType", "Sender", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
