// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

package sjtu.opennet.textilepb;

public final class Mobile {
  private Mobile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MobileEventType}
   */
  public enum MobileEventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NODE_START = 0;</code>
     */
    NODE_START(0),
    /**
     * <code>NODE_ONLINE = 1;</code>
     */
    NODE_ONLINE(1),
    /**
     * <code>NODE_STOP = 2;</code>
     */
    NODE_STOP(2),
    /**
     * <code>ACCOUNT_UPDATE = 10;</code>
     */
    ACCOUNT_UPDATE(10),
    /**
     * <code>THREAD_UPDATE = 11;</code>
     */
    THREAD_UPDATE(11),
    /**
     * <code>NOTIFICATION = 12;</code>
     */
    NOTIFICATION(12),
    /**
     * <code>QUERY_RESPONSE = 20;</code>
     */
    QUERY_RESPONSE(20),
    /**
     * <code>CAFE_SYNC_GROUP_UPDATE = 30;</code>
     */
    CAFE_SYNC_GROUP_UPDATE(30),
    /**
     * <code>CAFE_SYNC_GROUP_COMPLETE = 31;</code>
     */
    CAFE_SYNC_GROUP_COMPLETE(31),
    /**
     * <code>CAFE_SYNC_GROUP_FAILED = 32;</code>
     */
    CAFE_SYNC_GROUP_FAILED(32),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NODE_START = 0;</code>
     */
    public static final int NODE_START_VALUE = 0;
    /**
     * <code>NODE_ONLINE = 1;</code>
     */
    public static final int NODE_ONLINE_VALUE = 1;
    /**
     * <code>NODE_STOP = 2;</code>
     */
    public static final int NODE_STOP_VALUE = 2;
    /**
     * <code>ACCOUNT_UPDATE = 10;</code>
     */
    public static final int ACCOUNT_UPDATE_VALUE = 10;
    /**
     * <code>THREAD_UPDATE = 11;</code>
     */
    public static final int THREAD_UPDATE_VALUE = 11;
    /**
     * <code>NOTIFICATION = 12;</code>
     */
    public static final int NOTIFICATION_VALUE = 12;
    /**
     * <code>QUERY_RESPONSE = 20;</code>
     */
    public static final int QUERY_RESPONSE_VALUE = 20;
    /**
     * <code>CAFE_SYNC_GROUP_UPDATE = 30;</code>
     */
    public static final int CAFE_SYNC_GROUP_UPDATE_VALUE = 30;
    /**
     * <code>CAFE_SYNC_GROUP_COMPLETE = 31;</code>
     */
    public static final int CAFE_SYNC_GROUP_COMPLETE_VALUE = 31;
    /**
     * <code>CAFE_SYNC_GROUP_FAILED = 32;</code>
     */
    public static final int CAFE_SYNC_GROUP_FAILED_VALUE = 32;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MobileEventType valueOf(int value) {
      return forNumber(value);
    }

    public static MobileEventType forNumber(int value) {
      switch (value) {
        case 0: return NODE_START;
        case 1: return NODE_ONLINE;
        case 2: return NODE_STOP;
        case 10: return ACCOUNT_UPDATE;
        case 11: return THREAD_UPDATE;
        case 12: return NOTIFICATION;
        case 20: return QUERY_RESPONSE;
        case 30: return CAFE_SYNC_GROUP_UPDATE;
        case 31: return CAFE_SYNC_GROUP_COMPLETE;
        case 32: return CAFE_SYNC_GROUP_FAILED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MobileEventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MobileEventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MobileEventType>() {
            public MobileEventType findValueByNumber(int number) {
              return MobileEventType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return sjtu.opennet.textilepb.Mobile.getDescriptor().getEnumTypes().get(0);
    }

    private static final MobileEventType[] VALUES = values();

    public static MobileEventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MobileEventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MobileEventType)
  }

  public interface MobileWalletAccountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MobileWalletAccount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string seed = 1;</code>
     */
    java.lang.String getSeed();
    /**
     * <code>string seed = 1;</code>
     */
    com.google.protobuf.ByteString
        getSeedBytes();

    /**
     * <code>string address = 2;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 2;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code MobileWalletAccount}
   */
  public  static final class MobileWalletAccount extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MobileWalletAccount)
      MobileWalletAccountOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MobileWalletAccount.newBuilder() to construct.
    private MobileWalletAccount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MobileWalletAccount() {
      seed_ = "";
      address_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MobileWalletAccount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              seed_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sjtu.opennet.textilepb.Mobile.internal_static_MobileWalletAccount_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sjtu.opennet.textilepb.Mobile.internal_static_MobileWalletAccount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sjtu.opennet.textilepb.Mobile.MobileWalletAccount.class, sjtu.opennet.textilepb.Mobile.MobileWalletAccount.Builder.class);
    }

    public static final int SEED_FIELD_NUMBER = 1;
    private volatile java.lang.Object seed_;
    /**
     * <code>string seed = 1;</code>
     */
    public java.lang.String getSeed() {
      java.lang.Object ref = seed_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        seed_ = s;
        return s;
      }
    }
    /**
     * <code>string seed = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSeedBytes() {
      java.lang.Object ref = seed_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        seed_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 2;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSeedBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, seed_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, address_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSeedBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, seed_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, address_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sjtu.opennet.textilepb.Mobile.MobileWalletAccount)) {
        return super.equals(obj);
      }
      sjtu.opennet.textilepb.Mobile.MobileWalletAccount other = (sjtu.opennet.textilepb.Mobile.MobileWalletAccount) obj;

      boolean result = true;
      result = result && getSeed()
          .equals(other.getSeed());
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SEED_FIELD_NUMBER;
      hash = (53 * hash) + getSeed().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sjtu.opennet.textilepb.Mobile.MobileWalletAccount parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileWalletAccount parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileWalletAccount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileWalletAccount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileWalletAccount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileWalletAccount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileWalletAccount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileWalletAccount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileWalletAccount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileWalletAccount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileWalletAccount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileWalletAccount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sjtu.opennet.textilepb.Mobile.MobileWalletAccount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MobileWalletAccount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MobileWalletAccount)
        sjtu.opennet.textilepb.Mobile.MobileWalletAccountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sjtu.opennet.textilepb.Mobile.internal_static_MobileWalletAccount_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sjtu.opennet.textilepb.Mobile.internal_static_MobileWalletAccount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sjtu.opennet.textilepb.Mobile.MobileWalletAccount.class, sjtu.opennet.textilepb.Mobile.MobileWalletAccount.Builder.class);
      }

      // Construct using sjtu.opennet.textilepb.Mobile.MobileWalletAccount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        seed_ = "";

        address_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sjtu.opennet.textilepb.Mobile.internal_static_MobileWalletAccount_descriptor;
      }

      @java.lang.Override
      public sjtu.opennet.textilepb.Mobile.MobileWalletAccount getDefaultInstanceForType() {
        return sjtu.opennet.textilepb.Mobile.MobileWalletAccount.getDefaultInstance();
      }

      @java.lang.Override
      public sjtu.opennet.textilepb.Mobile.MobileWalletAccount build() {
        sjtu.opennet.textilepb.Mobile.MobileWalletAccount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sjtu.opennet.textilepb.Mobile.MobileWalletAccount buildPartial() {
        sjtu.opennet.textilepb.Mobile.MobileWalletAccount result = new sjtu.opennet.textilepb.Mobile.MobileWalletAccount(this);
        result.seed_ = seed_;
        result.address_ = address_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sjtu.opennet.textilepb.Mobile.MobileWalletAccount) {
          return mergeFrom((sjtu.opennet.textilepb.Mobile.MobileWalletAccount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sjtu.opennet.textilepb.Mobile.MobileWalletAccount other) {
        if (other == sjtu.opennet.textilepb.Mobile.MobileWalletAccount.getDefaultInstance()) return this;
        if (!other.getSeed().isEmpty()) {
          seed_ = other.seed_;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sjtu.opennet.textilepb.Mobile.MobileWalletAccount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sjtu.opennet.textilepb.Mobile.MobileWalletAccount) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object seed_ = "";
      /**
       * <code>string seed = 1;</code>
       */
      public java.lang.String getSeed() {
        java.lang.Object ref = seed_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          seed_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string seed = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSeedBytes() {
        java.lang.Object ref = seed_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          seed_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string seed = 1;</code>
       */
      public Builder setSeed(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        seed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string seed = 1;</code>
       */
      public Builder clearSeed() {
        
        seed_ = getDefaultInstance().getSeed();
        onChanged();
        return this;
      }
      /**
       * <code>string seed = 1;</code>
       */
      public Builder setSeedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        seed_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 2;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 2;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 2;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 2;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MobileWalletAccount)
    }

    // @@protoc_insertion_point(class_scope:MobileWalletAccount)
    private static final sjtu.opennet.textilepb.Mobile.MobileWalletAccount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sjtu.opennet.textilepb.Mobile.MobileWalletAccount();
    }

    public static sjtu.opennet.textilepb.Mobile.MobileWalletAccount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MobileWalletAccount>
        PARSER = new com.google.protobuf.AbstractParser<MobileWalletAccount>() {
      @java.lang.Override
      public MobileWalletAccount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MobileWalletAccount(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MobileWalletAccount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MobileWalletAccount> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sjtu.opennet.textilepb.Mobile.MobileWalletAccount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MobileQueryEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MobileQueryEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.MobileQueryEvent.Type type = 2;</code>
     */
    int getTypeValue();
    /**
     * <code>.MobileQueryEvent.Type type = 2;</code>
     */
    sjtu.opennet.textilepb.Mobile.MobileQueryEvent.Type getType();

    /**
     * <code>.QueryResult data = 3;</code>
     */
    boolean hasData();
    /**
     * <code>.QueryResult data = 3;</code>
     */
    sjtu.opennet.textilepb.QueryOuterClass.QueryResult getData();
    /**
     * <code>.QueryResult data = 3;</code>
     */
    sjtu.opennet.textilepb.QueryOuterClass.QueryResultOrBuilder getDataOrBuilder();

    /**
     * <code>.Error error = 4;</code>
     */
    boolean hasError();
    /**
     * <code>.Error error = 4;</code>
     */
    sjtu.opennet.textilepb.MessageOuterClass.Error getError();
    /**
     * <code>.Error error = 4;</code>
     */
    sjtu.opennet.textilepb.MessageOuterClass.ErrorOrBuilder getErrorOrBuilder();
  }
  /**
   * Protobuf type {@code MobileQueryEvent}
   */
  public  static final class MobileQueryEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MobileQueryEvent)
      MobileQueryEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MobileQueryEvent.newBuilder() to construct.
    private MobileQueryEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MobileQueryEvent() {
      id_ = "";
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MobileQueryEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              sjtu.opennet.textilepb.QueryOuterClass.QueryResult.Builder subBuilder = null;
              if (data_ != null) {
                subBuilder = data_.toBuilder();
              }
              data_ = input.readMessage(sjtu.opennet.textilepb.QueryOuterClass.QueryResult.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(data_);
                data_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              sjtu.opennet.textilepb.MessageOuterClass.Error.Builder subBuilder = null;
              if (error_ != null) {
                subBuilder = error_.toBuilder();
              }
              error_ = input.readMessage(sjtu.opennet.textilepb.MessageOuterClass.Error.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(error_);
                error_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sjtu.opennet.textilepb.Mobile.internal_static_MobileQueryEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sjtu.opennet.textilepb.Mobile.internal_static_MobileQueryEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sjtu.opennet.textilepb.Mobile.MobileQueryEvent.class, sjtu.opennet.textilepb.Mobile.MobileQueryEvent.Builder.class);
    }

    /**
     * Protobuf enum {@code MobileQueryEvent.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DATA = 0;</code>
       */
      DATA(0),
      /**
       * <code>DONE = 1;</code>
       */
      DONE(1),
      /**
       * <code>ERROR = 2;</code>
       */
      ERROR(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>DATA = 0;</code>
       */
      public static final int DATA_VALUE = 0;
      /**
       * <code>DONE = 1;</code>
       */
      public static final int DONE_VALUE = 1;
      /**
       * <code>ERROR = 2;</code>
       */
      public static final int ERROR_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return DATA;
          case 1: return DONE;
          case 2: return ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return sjtu.opennet.textilepb.Mobile.MobileQueryEvent.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MobileQueryEvent.Type)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.MobileQueryEvent.Type type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.MobileQueryEvent.Type type = 2;</code>
     */
    public sjtu.opennet.textilepb.Mobile.MobileQueryEvent.Type getType() {
      @SuppressWarnings("deprecation")
      sjtu.opennet.textilepb.Mobile.MobileQueryEvent.Type result = sjtu.opennet.textilepb.Mobile.MobileQueryEvent.Type.valueOf(type_);
      return result == null ? sjtu.opennet.textilepb.Mobile.MobileQueryEvent.Type.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private sjtu.opennet.textilepb.QueryOuterClass.QueryResult data_;
    /**
     * <code>.QueryResult data = 3;</code>
     */
    public boolean hasData() {
      return data_ != null;
    }
    /**
     * <code>.QueryResult data = 3;</code>
     */
    public sjtu.opennet.textilepb.QueryOuterClass.QueryResult getData() {
      return data_ == null ? sjtu.opennet.textilepb.QueryOuterClass.QueryResult.getDefaultInstance() : data_;
    }
    /**
     * <code>.QueryResult data = 3;</code>
     */
    public sjtu.opennet.textilepb.QueryOuterClass.QueryResultOrBuilder getDataOrBuilder() {
      return getData();
    }

    public static final int ERROR_FIELD_NUMBER = 4;
    private sjtu.opennet.textilepb.MessageOuterClass.Error error_;
    /**
     * <code>.Error error = 4;</code>
     */
    public boolean hasError() {
      return error_ != null;
    }
    /**
     * <code>.Error error = 4;</code>
     */
    public sjtu.opennet.textilepb.MessageOuterClass.Error getError() {
      return error_ == null ? sjtu.opennet.textilepb.MessageOuterClass.Error.getDefaultInstance() : error_;
    }
    /**
     * <code>.Error error = 4;</code>
     */
    public sjtu.opennet.textilepb.MessageOuterClass.ErrorOrBuilder getErrorOrBuilder() {
      return getError();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (type_ != sjtu.opennet.textilepb.Mobile.MobileQueryEvent.Type.DATA.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (data_ != null) {
        output.writeMessage(3, getData());
      }
      if (error_ != null) {
        output.writeMessage(4, getError());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (type_ != sjtu.opennet.textilepb.Mobile.MobileQueryEvent.Type.DATA.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (data_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getData());
      }
      if (error_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getError());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sjtu.opennet.textilepb.Mobile.MobileQueryEvent)) {
        return super.equals(obj);
      }
      sjtu.opennet.textilepb.Mobile.MobileQueryEvent other = (sjtu.opennet.textilepb.Mobile.MobileQueryEvent) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && type_ == other.type_;
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && (hasError() == other.hasError());
      if (hasError()) {
        result = result && getError()
            .equals(other.getError());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      if (hasError()) {
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getError().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sjtu.opennet.textilepb.Mobile.MobileQueryEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileQueryEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileQueryEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileQueryEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileQueryEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileQueryEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileQueryEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileQueryEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileQueryEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileQueryEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileQueryEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sjtu.opennet.textilepb.Mobile.MobileQueryEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sjtu.opennet.textilepb.Mobile.MobileQueryEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MobileQueryEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MobileQueryEvent)
        sjtu.opennet.textilepb.Mobile.MobileQueryEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sjtu.opennet.textilepb.Mobile.internal_static_MobileQueryEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sjtu.opennet.textilepb.Mobile.internal_static_MobileQueryEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sjtu.opennet.textilepb.Mobile.MobileQueryEvent.class, sjtu.opennet.textilepb.Mobile.MobileQueryEvent.Builder.class);
      }

      // Construct using sjtu.opennet.textilepb.Mobile.MobileQueryEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        type_ = 0;

        if (dataBuilder_ == null) {
          data_ = null;
        } else {
          data_ = null;
          dataBuilder_ = null;
        }
        if (errorBuilder_ == null) {
          error_ = null;
        } else {
          error_ = null;
          errorBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sjtu.opennet.textilepb.Mobile.internal_static_MobileQueryEvent_descriptor;
      }

      @java.lang.Override
      public sjtu.opennet.textilepb.Mobile.MobileQueryEvent getDefaultInstanceForType() {
        return sjtu.opennet.textilepb.Mobile.MobileQueryEvent.getDefaultInstance();
      }

      @java.lang.Override
      public sjtu.opennet.textilepb.Mobile.MobileQueryEvent build() {
        sjtu.opennet.textilepb.Mobile.MobileQueryEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sjtu.opennet.textilepb.Mobile.MobileQueryEvent buildPartial() {
        sjtu.opennet.textilepb.Mobile.MobileQueryEvent result = new sjtu.opennet.textilepb.Mobile.MobileQueryEvent(this);
        result.id_ = id_;
        result.type_ = type_;
        if (dataBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        if (errorBuilder_ == null) {
          result.error_ = error_;
        } else {
          result.error_ = errorBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sjtu.opennet.textilepb.Mobile.MobileQueryEvent) {
          return mergeFrom((sjtu.opennet.textilepb.Mobile.MobileQueryEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sjtu.opennet.textilepb.Mobile.MobileQueryEvent other) {
        if (other == sjtu.opennet.textilepb.Mobile.MobileQueryEvent.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        if (other.hasError()) {
          mergeError(other.getError());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sjtu.opennet.textilepb.Mobile.MobileQueryEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sjtu.opennet.textilepb.Mobile.MobileQueryEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.MobileQueryEvent.Type type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.MobileQueryEvent.Type type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MobileQueryEvent.Type type = 2;</code>
       */
      public sjtu.opennet.textilepb.Mobile.MobileQueryEvent.Type getType() {
        @SuppressWarnings("deprecation")
        sjtu.opennet.textilepb.Mobile.MobileQueryEvent.Type result = sjtu.opennet.textilepb.Mobile.MobileQueryEvent.Type.valueOf(type_);
        return result == null ? sjtu.opennet.textilepb.Mobile.MobileQueryEvent.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.MobileQueryEvent.Type type = 2;</code>
       */
      public Builder setType(sjtu.opennet.textilepb.Mobile.MobileQueryEvent.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MobileQueryEvent.Type type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private sjtu.opennet.textilepb.QueryOuterClass.QueryResult data_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          sjtu.opennet.textilepb.QueryOuterClass.QueryResult, sjtu.opennet.textilepb.QueryOuterClass.QueryResult.Builder, sjtu.opennet.textilepb.QueryOuterClass.QueryResultOrBuilder> dataBuilder_;
      /**
       * <code>.QueryResult data = 3;</code>
       */
      public boolean hasData() {
        return dataBuilder_ != null || data_ != null;
      }
      /**
       * <code>.QueryResult data = 3;</code>
       */
      public sjtu.opennet.textilepb.QueryOuterClass.QueryResult getData() {
        if (dataBuilder_ == null) {
          return data_ == null ? sjtu.opennet.textilepb.QueryOuterClass.QueryResult.getDefaultInstance() : data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      /**
       * <code>.QueryResult data = 3;</code>
       */
      public Builder setData(sjtu.opennet.textilepb.QueryOuterClass.QueryResult value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.QueryResult data = 3;</code>
       */
      public Builder setData(
          sjtu.opennet.textilepb.QueryOuterClass.QueryResult.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.QueryResult data = 3;</code>
       */
      public Builder mergeData(sjtu.opennet.textilepb.QueryOuterClass.QueryResult value) {
        if (dataBuilder_ == null) {
          if (data_ != null) {
            data_ =
              sjtu.opennet.textilepb.QueryOuterClass.QueryResult.newBuilder(data_).mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          dataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.QueryResult data = 3;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = null;
          onChanged();
        } else {
          data_ = null;
          dataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.QueryResult data = 3;</code>
       */
      public sjtu.opennet.textilepb.QueryOuterClass.QueryResult.Builder getDataBuilder() {
        
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.QueryResult data = 3;</code>
       */
      public sjtu.opennet.textilepb.QueryOuterClass.QueryResultOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_ == null ?
              sjtu.opennet.textilepb.QueryOuterClass.QueryResult.getDefaultInstance() : data_;
        }
      }
      /**
       * <code>.QueryResult data = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          sjtu.opennet.textilepb.QueryOuterClass.QueryResult, sjtu.opennet.textilepb.QueryOuterClass.QueryResult.Builder, sjtu.opennet.textilepb.QueryOuterClass.QueryResultOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              sjtu.opennet.textilepb.QueryOuterClass.QueryResult, sjtu.opennet.textilepb.QueryOuterClass.QueryResult.Builder, sjtu.opennet.textilepb.QueryOuterClass.QueryResultOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      private sjtu.opennet.textilepb.MessageOuterClass.Error error_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          sjtu.opennet.textilepb.MessageOuterClass.Error, sjtu.opennet.textilepb.MessageOuterClass.Error.Builder, sjtu.opennet.textilepb.MessageOuterClass.ErrorOrBuilder> errorBuilder_;
      /**
       * <code>.Error error = 4;</code>
       */
      public boolean hasError() {
        return errorBuilder_ != null || error_ != null;
      }
      /**
       * <code>.Error error = 4;</code>
       */
      public sjtu.opennet.textilepb.MessageOuterClass.Error getError() {
        if (errorBuilder_ == null) {
          return error_ == null ? sjtu.opennet.textilepb.MessageOuterClass.Error.getDefaultInstance() : error_;
        } else {
          return errorBuilder_.getMessage();
        }
      }
      /**
       * <code>.Error error = 4;</code>
       */
      public Builder setError(sjtu.opennet.textilepb.MessageOuterClass.Error value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          error_ = value;
          onChanged();
        } else {
          errorBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Error error = 4;</code>
       */
      public Builder setError(
          sjtu.opennet.textilepb.MessageOuterClass.Error.Builder builderForValue) {
        if (errorBuilder_ == null) {
          error_ = builderForValue.build();
          onChanged();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Error error = 4;</code>
       */
      public Builder mergeError(sjtu.opennet.textilepb.MessageOuterClass.Error value) {
        if (errorBuilder_ == null) {
          if (error_ != null) {
            error_ =
              sjtu.opennet.textilepb.MessageOuterClass.Error.newBuilder(error_).mergeFrom(value).buildPartial();
          } else {
            error_ = value;
          }
          onChanged();
        } else {
          errorBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Error error = 4;</code>
       */
      public Builder clearError() {
        if (errorBuilder_ == null) {
          error_ = null;
          onChanged();
        } else {
          error_ = null;
          errorBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Error error = 4;</code>
       */
      public sjtu.opennet.textilepb.MessageOuterClass.Error.Builder getErrorBuilder() {
        
        onChanged();
        return getErrorFieldBuilder().getBuilder();
      }
      /**
       * <code>.Error error = 4;</code>
       */
      public sjtu.opennet.textilepb.MessageOuterClass.ErrorOrBuilder getErrorOrBuilder() {
        if (errorBuilder_ != null) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          return error_ == null ?
              sjtu.opennet.textilepb.MessageOuterClass.Error.getDefaultInstance() : error_;
        }
      }
      /**
       * <code>.Error error = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          sjtu.opennet.textilepb.MessageOuterClass.Error, sjtu.opennet.textilepb.MessageOuterClass.Error.Builder, sjtu.opennet.textilepb.MessageOuterClass.ErrorOrBuilder> 
          getErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              sjtu.opennet.textilepb.MessageOuterClass.Error, sjtu.opennet.textilepb.MessageOuterClass.Error.Builder, sjtu.opennet.textilepb.MessageOuterClass.ErrorOrBuilder>(
                  getError(),
                  getParentForChildren(),
                  isClean());
          error_ = null;
        }
        return errorBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MobileQueryEvent)
    }

    // @@protoc_insertion_point(class_scope:MobileQueryEvent)
    private static final sjtu.opennet.textilepb.Mobile.MobileQueryEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sjtu.opennet.textilepb.Mobile.MobileQueryEvent();
    }

    public static sjtu.opennet.textilepb.Mobile.MobileQueryEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MobileQueryEvent>
        PARSER = new com.google.protobuf.AbstractParser<MobileQueryEvent>() {
      @java.lang.Override
      public MobileQueryEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MobileQueryEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MobileQueryEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MobileQueryEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sjtu.opennet.textilepb.Mobile.MobileQueryEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MobileWalletAccount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MobileWalletAccount_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MobileQueryEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MobileQueryEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014mobile.proto\032\013query.proto\032\rmessage.pro" +
      "to\"4\n\023MobileWalletAccount\022\014\n\004seed\030\001 \001(\t\022" +
      "\017\n\007address\030\002 \001(\t\"\236\001\n\020MobileQueryEvent\022\n\n" +
      "\002id\030\001 \001(\t\022$\n\004type\030\002 \001(\0162\026.MobileQueryEve" +
      "nt.Type\022\032\n\004data\030\003 \001(\0132\014.QueryResult\022\025\n\005e" +
      "rror\030\004 \001(\0132\006.Error\"%\n\004Type\022\010\n\004DATA\020\000\022\010\n\004" +
      "DONE\020\001\022\t\n\005ERROR\020\002*\344\001\n\017MobileEventType\022\016\n" +
      "\nNODE_START\020\000\022\017\n\013NODE_ONLINE\020\001\022\r\n\tNODE_S" +
      "TOP\020\002\022\022\n\016ACCOUNT_UPDATE\020\n\022\021\n\rTHREAD_UPDA" +
      "TE\020\013\022\020\n\014NOTIFICATION\020\014\022\022\n\016QUERY_RESPONSE" +
      "\020\024\022\032\n\026CAFE_SYNC_GROUP_UPDATE\020\036\022\034\n\030CAFE_S" +
      "YNC_GROUP_COMPLETE\020\037\022\032\n\026CAFE_SYNC_GROUP_" +
      "FAILED\020 B\034\n\026sjtu.opennet.textilepbZ\002pbb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          sjtu.opennet.textilepb.QueryOuterClass.getDescriptor(),
          sjtu.opennet.textilepb.MessageOuterClass.getDescriptor(),
        }, assigner);
    internal_static_MobileWalletAccount_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MobileWalletAccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MobileWalletAccount_descriptor,
        new java.lang.String[] { "Seed", "Address", });
    internal_static_MobileQueryEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MobileQueryEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MobileQueryEvent_descriptor,
        new java.lang.String[] { "Id", "Type", "Data", "Error", });
    sjtu.opennet.textilepb.QueryOuterClass.getDescriptor();
    sjtu.opennet.textilepb.MessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
